version: "3.9"

services:
  web:
    build: .
    container_name: radarmapa_web
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: radarmapa_db
    restart: always
    environment:
      POSTGRES_DB: radar
      POSTGRES_USER: radar
      POSTGRES_PASSWORD: radar
